#!/usr/bin/env bash
#Configure web-02 like web-01 with a custom response header
sudo apt-get update
sudo apt install haproxy=1.5\*
FILE=/etc/haproxy/haproxy.cfg
echo -e "listen appname :80
\tmode http
\tbalance roundrobin
\tserver 378-web-01 35.237.167.147:80 check
\tserver 378-web-02 34.73.249.164:80 check" | sudo tee -a $FILE
sudo service haproxy restart
