#!/usr/bin/env bash
# Fizz Buzz
f='Fizz'
b='Buzz'
fb='FizzBuzz'
i=1
while (( i < 101 )); do
      if (( i % 15 == 0 ))
      	 then
	 echo "$fb"
      elif (( i % 3 == 0 ))
      	 then
	 echo "$f"
      elif (( i % 5 == 0 ))
      	 then
	 echo "$b"
      else
         echo "$i"
      fi
      i="$(( i + 1 ))"
done
