#!/usr/bin/env bash
# displays numbers from 1 to 20 and 4, 9, 17 use case:
i=1
j=20
while (( i <= j)); do
case $i in
5)
echo "bad luck from China"
;;
10)
echo "bad luck from Japan"
;;
18)
echo "bad luck from Italy"
;;
esac
echo "$i"
i="$(( i + 1 ))"
done