#!/usr/bin/env bash
# script that gives you information about the holbertonschool file
h="holbertonschool"
if [ -e "$h" ]
then
echo "$h file exists"
if [ ! -s "$h" ]
then
echo "$h file is empty"
else
echo "$h file is not empty"
fi
if [ -f "$h" ]
then
echo "$h is a regular file"
fi
else
echo "$h file does not exist"
fi
