#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page
apt-get update
apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i '30i\\tlocation \/redirect_me {\n\t\treturn 301 http://google.com;\n}\n' /etc/nginx/sites-available/default
service nginx restart
